version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"           # Root directory of your project (where settings.gradle.kts is)
    schedule:
      interval: "weekly"     # Or "daily", "monthly", etc.
